// <auto-generated />
using System;
using EUC.Profile.Buddy.Web.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EUC.Profile.Buddy.Web.Migrations
{
    [DbContext(typeof(ProfileDataRepository))]
    partial class ProfileDataRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("EUC.Profile.Buddy.Web.Repositories.Entities.TaskInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TaskExecuted")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TaskRunTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskInformation");
                });

            modelBuilder.Entity("EUC.Profile.Buddy.Web.Repositories.Entities.UserProfileSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ProfileAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TempSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfileSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
